Task ansible_ui.tasks.install_role[630ac507-d41e-43c6-a0c4-8602b01590df] raised unexpected: OperationalError('no such column: ansible_ui_role.install_from',)
Traceback (most recent call last):
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: ansible_ui_role.install_from

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/guang/projects/AnsibleUI/ansible_ui/tasks.py", line 55, in install_role
    role = get_object_or_none(Role, id=tid)
  File "/Users/guang/projects/AnsibleUI/ansible_ui/utils.py", line 17, in get_object_or_none
    obj = model.objects.get(**kwargs)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/guang/.virtualenvs/ansible/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 296, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: ansible_ui_role.install_from
